const coursesSeedData = [
  {
    title: "VAPT Analyst",
    slug: "vapt-analyst",
    shortDescription: "Vulnerability Assessment & Penetration Testing Analyst Program",
    description: "Master Vulnerability Assessment & Penetration Testing (VAPT). Conduct security audits, web app vulnerability scanning, network exploitation, and write enterprise audit reports.",
    thumbnail: "/images/cyber.png",
    category: "Cyber Security",
    level: "Beginner to Advanced",
    price: 4999900,
    discountPrice: 2999900,
    currency: "INR",
    duration: "6 Months (240 Hours Live Practical)",
    bannerClass: "cyber-bg",
    bannerIcon: "fa-solid fa-user-secret",
    prereq: "Basic Networking and OS concepts",
    cert: "Netcradus Certified VAPT Analyst",
    highlights: [
      "Vulnerability Assessment & Penetration Testing",
      "Network & Web Application Security",
      "Bug Bounty & Corporate Audit Reports"
    ],
    tools: ["Metasploit", "Wireshark", "Burp Suite Pro", "Nmap", "Kali Linux", "OWASP ZAP"],
    roles: ["VAPT Analyst", "Penetration Tester", "Cyber Security Auditor"],
    requirements: ["Basic Networking and OS concepts"],
    learningOutcomes: [
      "Information Gathering, Footprinting & Reconnaissance",
      "Network Pentesting & Vulnerability Assessment",
      "Web Application Pentesting (OWASP Top 10)",
      "System Hacking, Privilege Escalation & Persistence"
    ],
    skills: ["Metasploit", "Wireshark", "Burp Suite Pro", "Nmap", "Kali Linux", "OWASP ZAP"],
    tags: ["Cyber Security", "VAPT", "Ethical Hacking"],
    published: true,
    featured: true
  },
  {
    title: "Penetration Testing",
    slug: "penetration-testing",
    shortDescription: "Advanced Penetration Testing & Ethical Hacking Program",
    description: "Deep dive into advanced penetration testing techniques. Master Active Directory hacking, wireless security, privilege escalation, and red team engagement strategies.",
    thumbnail: "/images/cyber.png",
    category: "Cyber Security",
    level: "Intermediate to Advanced",
    price: 5499900,
    discountPrice: 3299900,
    currency: "INR",
    duration: "6 Months (240 Hours Hands-on)",
    bannerClass: "cyber-bg",
    bannerIcon: "fa-solid fa-bug",
    prereq: "Linux & Networking fundamentals",
    cert: "Netcradus Certified Penetration Tester (NCPT)",
    highlights: [
      "Active Directory Pentesting & Exploitation",
      "Privilege Escalation & Evasion Techniques",
      "Red Team Operations & Offensive Security"
    ],
    tools: ["Kali Linux", "Metasploit", "Burp Suite", "BloodHound", "Cobalt Strike", "Nmap"],
    roles: ["Penetration Tester", "Ethical Hacker", "Red Team Specialist"],
    requirements: ["Linux & Networking fundamentals"],
    learningOutcomes: [
      "Network Scanning & Vulnerability Analysis",
      "Active Directory Hacking & Lateral Movement",
      "Web & Infrastructure Exploitation",
      "Wireless & Social Engineering Attacks"
    ],
    skills: ["Kali Linux", "Metasploit", "Burp Suite", "BloodHound", "Nmap"],
    tags: ["Cyber Security", "Penetration Testing", "Red Teaming"],
    published: true,
    featured: true
  },
  {
    title: "SOC Analyst",
    slug: "soc-analyst",
    shortDescription: "SOC Analyst & Incident Response Specialist",
    description: "Audit security logs, detect cyber threats, and defend against ransomware. Master SIEM operations in Splunk Enterprise, malware forensics, and protocol auditing with Wireshark.",
    thumbnail: "/images/soc.png",
    category: "Cyber Security",
    level: "Beginner to Intermediate",
    price: 4499900,
    discountPrice: 2699900,
    currency: "INR",
    duration: "5 Months (200 Hours SOC Lab)",
    bannerClass: "devops-bg",
    bannerIcon: "fa-solid fa-shield-virus",
    prereq: "Networking & Security Basics",
    cert: "Netcradus Certified SOC Analyst (NCSA)",
    highlights: [
      "Splunk Enterprise SIEM Operations",
      "Malware Analysis & Incident Response",
      "Threat Hunting & Forensic Auditing"
    ],
    tools: ["Splunk Enterprise", "Wireshark", "QRadar", "Elastic SIEM", "YARA", "Autopsy"],
    roles: ["L1/L2 SOC Analyst", "Incident Responder", "Threat Hunter"],
    requirements: ["Networking & Security Basics"],
    learningOutcomes: [
      "SOC Operations Overview & Threat Intelligence",
      "Packet Analysis & Protocol Auditing with Wireshark",
      "SIEM Log Analysis & Rule Creation with Splunk",
      "Incident Playbooks & Ransomware Defense"
    ],
    skills: ["Splunk Enterprise", "Wireshark", "QRadar", "Elastic SIEM", "YARA"],
    tags: ["Cyber Security", "SOC", "Incident Response", "SIEM"],
    published: true,
    featured: false
  },
  {
    title: "Cloud Security Analyst",
    slug: "cloud-security-analyst",
    shortDescription: "Cloud Security & Infrastructure Defense Analyst",
    description: "Protect multi-cloud infrastructures across AWS, Azure, and GCP. Master IAM policy configuration, container/Kubernetes security, and cloud compliance frameworks.",
    thumbnail: "/images/cloud.png",
    category: "Cyber Security",
    level: "Intermediate",
    price: 4999900,
    discountPrice: 2999900,
    currency: "INR",
    duration: "5 Months (200 Hours Multi-Cloud)",
    bannerClass: "cloud-bg",
    bannerIcon: "fa-solid fa-cloud-shield",
    prereq: "Basic Cloud & Linux knowledge",
    cert: "Netcradus Certified Cloud Security Specialist",
    highlights: [
      "AWS & Azure Security Architecture",
      "Container & Kubernetes Security",
      "Cloud IAM & DevSecOps Integration"
    ],
    tools: ["AWS Security Hub", "Azure Sentinel", "Prisma Cloud", "Terraform", "Docker", "Wiz"],
    roles: ["Cloud Security Analyst", "Cloud Security Engineer", "DevSecOps Engineer"],
    requirements: ["Basic Cloud & Linux knowledge"],
    learningOutcomes: [
      "Cloud Threat Landscape & Identity Access Management",
      "Securing AWS EC2, S3 & Azure Active Directory",
      "Docker & Kubernetes Container Hardening",
      "DevSecOps Pipeline Security & Compliance"
    ],
    skills: ["AWS Security Hub", "Azure Sentinel", "Terraform", "Docker", "Kubernetes Security"],
    tags: ["Cyber Security", "Cloud", "Cloud Security", "DevSecOps"],
    published: true,
    featured: false
  },
  {
    title: "Cloud Engineer",
    slug: "cloud-engineer",
    shortDescription: "AWS, Azure & GCP Multi-Cloud Infrastructure Engineer",
    description: "Architect scalable enterprise cloud solutions. Master AWS, Azure, and Google Cloud Platform along with Infrastructure as Code using Terraform and container orchestration with Kubernetes.",
    thumbnail: "/images/cloud.png",
    category: "Cloud",
    level: "Beginner to Pro",
    price: 3999900,
    discountPrice: 2499900,
    currency: "INR",
    duration: "5 Months (200 Hours Multi-Cloud)",
    bannerClass: "cloud-bg",
    bannerIcon: "fa-solid fa-cloud-arrow-up",
    prereq: "Basic Linux administration",
    cert: "Netcradus Certified Cloud Infrastructure Engineer",
    highlights: [
      "AWS, Azure & GCP Core Architecture",
      "Terraform Infrastructure as Code (IaC)",
      "Docker & Kubernetes Containerization"
    ],
    tools: ["AWS Console", "Azure Portal", "Google Cloud", "Terraform", "Kubernetes", "Docker"],
    roles: ["Cloud Solutions Engineer", "Cloud Systems Administrator", "DevOps Engineer"],
    requirements: ["Basic Linux administration"],
    learningOutcomes: [
      "Cloud Fundamentals & Virtual Private Cloud (VPC) Design",
      "AWS EC2, S3, Lambda & Azure Resource Management",
      "Infrastructure Provisioning with Terraform",
      "Kubernetes Cluster Deployment & Management"
    ],
    skills: ["AWS Console", "Azure Portal", "Terraform", "Kubernetes", "Docker", "Ansible"],
    tags: ["Cloud", "AWS", "Azure", "GCP", "DevOps", "Terraform"],
    published: true,
    featured: true
  },
  {
    title: "Linux Administrator",
    slug: "linux-administrator",
    shortDescription: "Enterprise Linux System Administration & Shell Scripting",
    description: "Master enterprise Linux administration on RHEL and Ubuntu Server. Learn shell scripting, system performance tuning, user & access controls, and network service configuration.",
    thumbnail: "/images/data.png",
    category: "Linux",
    level: "Beginner to Intermediate",
    price: 2999900,
    discountPrice: 1799900,
    currency: "INR",
    duration: "4 Months (160 Hours Practical)",
    bannerClass: "data-bg",
    bannerIcon: "fa-solid fa-terminal",
    prereq: "Computer operating fundamentals",
    cert: "Netcradus Certified Linux Administrator (RHCSA Prep)",
    highlights: [
      "Red Hat (RHEL) & Ubuntu Server Administration",
      "Bash Shell Scripting & Task Automation",
      "User Security, Storage Management & Hardening"
    ],
    tools: ["RHEL / CentOS", "Ubuntu Server", "Bash Scripting", "Ansible", "Systemd", "SELinux"],
    roles: ["Linux Administrator", "System Administrator", "Infrastructure Engineer"],
    requirements: ["Computer operating fundamentals"],
    learningOutcomes: [
      "Linux File System, Permissions & Access Control Lists",
      "User & Group Administration, Package Management",
      "Bash Shell Scripting & Automated Workflows",
      "Network Configuration, Systemd & Firewall Hardening"
    ],
    skills: ["Linux", "Bash", "RHEL", "Ubuntu", "Ansible", "SELinux"],
    tags: ["Linux", "System Administration", "RHEL", "Bash"],
    published: true,
    featured: false
  },
  {
    title: "AI/ML",
    slug: "ai-ml",
    shortDescription: "Artificial Intelligence, Machine Learning & Generative AI",
    description: "Develop intelligent AI systems. Master machine learning algorithms, deep neural networks, computer vision, transformers, and large language models (LLMs) with PyTorch and LangChain.",
    thumbnail: "/images/ai.png",
    category: "AI/ML",
    level: "Intermediate",
    price: 5999900,
    discountPrice: 3499900,
    currency: "INR",
    duration: "6 Months (240 Hours Live Coding)",
    bannerClass: "ai-bg",
    bannerIcon: "fa-solid fa-brain",
    prereq: "Python fundamentals & Basic Mathematics",
    cert: "Netcradus Certified AI & ML Specialist",
    highlights: [
      "Supervised & Unsupervised Machine Learning",
      "Deep Learning, Neural Networks & Computer Vision",
      "Generative AI, LLMs & Retrieval Augmented Generation (RAG)"
    ],
    tools: ["PyTorch", "TensorFlow", "OpenCV", "LangChain", "HuggingFace", "Docker"],
    roles: ["AI Engineer", "Machine Learning Specialist", "Data Scientist"],
    requirements: ["Python fundamentals & Basic Mathematics"],
    learningOutcomes: [
      "Python Data Science Libraries (NumPy, Pandas, Scikit-Learn)",
      "Supervised & Unsupervised Machine Learning",
      "Deep Learning with PyTorch & Convolutional Neural Networks",
      "Generative AI, Transformers, LangChain & LLM Deployment"
    ],
    skills: ["PyTorch", "TensorFlow", "OpenCV", "LangChain", "HuggingFace", "Python"],
    tags: ["AI/ML", "Machine Learning", "Generative AI", "Deep Learning"],
    published: true,
    featured: true
  },
  {
    title: "Network Security",
    slug: "network-security",
    shortDescription: "Enterprise Network Security & Firewall Engineering",
    description: "Design and implement secure network perimeters. Master Next-Generation Firewalls (Palo Alto, Cisco ASA), VPNs, Intrusion Prevention Systems (IPS), and network packet analysis.",
    thumbnail: "/images/cyber.png",
    category: "Cyber Security",
    level: "Beginner to Intermediate",
    price: 3999900,
    discountPrice: 2399900,
    currency: "INR",
    duration: "4 Months (160 Hours Network Labs)",
    bannerClass: "cyber-bg",
    bannerIcon: "fa-solid fa-network-wired",
    prereq: "Networking fundamentals",
    cert: "Netcradus Certified Network Security Engineer",
    highlights: [
      "Next-Gen Firewall Deployment (Palo Alto & Cisco ASA)",
      "Site-to-Site & Remote Access VPN Configuration",
      "IDS/IPS Rule Creation & Network Packet Auditing"
    ],
    tools: ["Cisco ASA", "Palo Alto Networks", "pfSense", "Wireshark", "GNS3", "Snort"],
    roles: ["Network Security Engineer", "Firewall Administrator", "Security Infrastructure Specialist"],
    requirements: ["Networking fundamentals"],
    learningOutcomes: [
      "Network Perimeter Defense Concepts & Segmentation",
      "Palo Alto & Cisco ASA Firewall Policy Management",
      "IPsec & SSL VPN Tunneling Architecture",
      "Intrusion Detection Systems (Snort/Suricata) & Wireshark"
    ],
    skills: ["Cisco ASA", "Palo Alto", "pfSense", "Wireshark", "Snort"],
    tags: ["Cyber Security", "Networking", "Network Security", "Firewalls"],
    published: true,
    featured: false
  },
  {
    title: "Network Engineer",
    slug: "network-engineer",
    shortDescription: "Enterprise Routing, Switching & Network Architecture",
    description: "Build scalable enterprise network infrastructures. Master TCP/IP protocols, VLAN configuration, routing protocols (OSPF, BGP), and Cisco IOS hardware administration.",
    thumbnail: "/images/data.png",
    category: "Networking",
    level: "Beginner to Intermediate",
    price: 3499900,
    discountPrice: 1999900,
    currency: "INR",
    duration: "5 Months (200 Hours Cisco Labs)",
    bannerClass: "data-bg",
    bannerIcon: "fa-solid fa-sitemap",
    prereq: "Basic computer networking interest",
    cert: "Netcradus Certified Network Engineer (CCNA Prep)",
    highlights: [
      "Cisco Router & Switch Configuration",
      "VLANs, Trunking, Spanning Tree & Subnetting",
      "Dynamic Routing Protocols (OSPF & BGP) Implementation"
    ],
    tools: ["Cisco Packet Tracer", "GNS3", "Wireshark", "Cisco IOS", "BGP", "OSPF"],
    roles: ["Network Engineer", "Network Administrator", "NOC Analyst"],
    requirements: ["Basic computer networking interest"],
    learningOutcomes: [
      "OSI Model & TCP/IP Protocol Stack Deep Dive",
      "IPv4/IPv6 Subnetting & IP Addressing Design",
      "Cisco Switch Configuration, VLANs & Trunking",
      "Routing Protocols (OSPF, EIGRP, BGP) & Network Troubleshooting"
    ],
    skills: ["Cisco IOS", "GNS3", "Wireshark", "BGP", "OSPF", "Subnetting"],
    tags: ["Networking", "Cisco", "CCNA", "Network Infrastructure"],
    published: true,
    featured: false
  }
];

module.exports = coursesSeedData;
